name: phpunit

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "8.1", "8.2", "8.3" ]
                symfony: [ "5.3", "6.0", "7.0" ]
                exclude:
                    -   php: "8.1"
                        symfony: "7.0"

        name: PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }} ${{ matrix.prefer }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require --no-interaction \
                        symfony/console:^${{ matrix.symfony }} \
                        symfony/var-dumper:^${{ matrix.symfony }} \

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
